{% set version = "0.2.0" %}

package:
  name: petulant-bear
  version: {{ version }}

source:
  url: https://github.com/ioos/petulant-bear/archive/v{{ version }}.tar.gz
  sha256: 5e81a3dba05db3e7616d2775d77da526ccf038fad39b590eae82e344eadadb64

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - netcdf4
    - numpy
    - lxml

test:
  imports:
    - petulantbear

about:
  home: https://github.com/ioos/petulant-bear
  license: GPL-3.0
  license_file: COPYING
  summary: 'Presents etree interface to netcdf4-python objects using NCML data model'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
