travis:
  secure:
    BINSTAR_TOKEN: XBo4qMoh9RnG1Z5qjPL3ENJTZC2UzXrRZAJh8dRydhV5jjTEAdvzf45IQG2INJDVS7qxQac96r4XqWnBFu5qM3QizzY7c5oK0/KPeIUSILCC+ZCE7OwkWf7IXKGpe5jg56Nm+qUc8Qq3uc6wRWhlXwxAy8D4Hxtp3G2CMKJzSQUswd//XDvfEEoHsQNl8NsgEyrSlb0RGj61VbfjZ69OhfFy92M0E5aOBYHL2FMHMz7lGbqENrf/HWWkis0Bd3+ewXX8bkXQCXguvfuN2pMxmDySD7o0Mv21eKSWEsjqcEiS3ySt/jzRDo+LUjzy5Apm7PWwQa860VcbKyxP1bekOQ49YHlbe7CSUlJUUMrPSh4tdh8LsL9h26YCmjrwl7fDoQNd8xlIuOaKr0TdRl6EQmjL+pUepYjD4e69fSgiie8uu1YKRZLr7WUSdJbaqj0b7YB3u3fjsQkcMWE7/F+64P9YdFBGLdl+8EkdGYBbW35EJpp28XMWefza22mQ0iXOODIYcklGMNRdmJp4/+3GaO6rrb4WIoUsf1NGtKPGvqO+BeiICPuwpQ5MiePI1F+PlGw3/IKkGiXhA/+cSUu3ZndBbbtiNnuGKSMP/qVimZM4bJ3KnLtW2A3MUl3oSq8Fp+lG3UT9ir2U6N1rDEYBolRhJpOhN7AVqhO9uhq7xRA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
